--- #YAML:1.0
name:               B-Hooks-OP-Annotation
version:            0.21
abstract:           Annotate and delegate hooked OPs
author:
    - chocolateboy <chocolate@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::Depends:  0.301
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
